HL_SLIPPAGE_PERCENTS = 0.5 

HL_SLIPPAGE = HL_SLIPPAGE_PERCENTS / 100

MIN_POSITION_TIME = 5* 60 
MAX_POSITION_TIME = 7 * 60

COINS = ['BTC', 'ETH', 'SOL']

HL_SIZE_DECIMALS = {'BTC': 5,'ETH': 4, 'SOL': 2}
HL_PRICE_DECIMALS = {'BTC': 0,'ETH': 2, 'SOL': 4}

HL_TAKER_FEE = 0.025 / 100
HL_MAKER_FEE = -0.002 / 100 

MIN_LEVERAGE = 5
MAX_LEVERAGE = 7

POSITION_SIZE = 70
SLEEP = 0.5
MIN_SLEEP_TIME = 1
MAX_SLEEP_TIME = 3

MAX_OPEN_POSITIONS = 5
MIN_OPEN_POSITIONS = 3