LONG = "LONG"
SHORT = "SHORT"
HYPERLIQUID_MAINNET_API_URL = "https://api.hyperliquid.xyz"
LONG_AEVO_SHORT_HYPERLIQUID = "LONG_AEVO_SHORT_HYPERLIQUID"
SHORT_AEVO_LONG_HYPERLIQUID = "SHORT_AEVO_LONG_HYPERLIQUID"

LONG_PERP1_SHORT_PERP2 = "LONG_PERP1_SHORT_PERP2"
LONG_PERP2_SHORT_PERP1 = "LONG_PERP2_SHORT_PERP1"

MAKER = "MAKER"
TAKER = "TAKER"

FILLED = "FILLED"
RESTING = "RESTING"
ERROR_FIELD = "ERROR_FIELD"
ERROR_POST_ORDER = "ERROR_POST_ORDER"
ERROR = "ERROR"